name: Build

on:
  workflow_call:
    inputs:
      jdk_version:
        description: The JDK version
        required: false
        type: string
        default: 21

jobs:
  build_maven_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK for x64
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.jdk_version }}
          distribution: 'temurin'
          architecture: x64

      - name: Build Service
        run: mvn --batch-mode --update-snapshots verify
        # Add other Maven-related steps if needed

      - name: Create staging directory and copy JAR
        run: |
          mkdir staging
          cp target/*.jar staging
