name: Build, Test, and Publish Docker image
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    uses: Ludogorie-Soft/dockerization-demo/.github/workflows/build.yml@main
    with:
      jdk_version: 21
  create_and_publish_docker_image:
    needs: build
    uses: Ludogorie-Soft/dockerization-demo/.github/workflows/create_and_publish_docker_image.yml@main
    secrets: inherit
    with:
      docker_file_path: ./Dockerfile

