name: Reuse Workflow from Another Repository

on:
  push:

jobs:
  reuse_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch workflow file from another repository
        run: |
          mkdir -p .github/workflows
          curl -o .github/workflows/build_branch.yml -L https://raw.githubusercontent.com/Ludogorie-Soft/ludogorie-soft-cicd/main/.github/workflows/maven/verify_and_build_main.yml

      - name: Run fetched workflow
        uses: ./.github/workflows/build_and_test.yml
        with:
          service-name: ${{ github.event.inputs.service-name }}
          java-version: "17"
          java-distribution: "oracle"
          sonar-project-key: "Ludogorie-Soft_dockerization-demo"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
